python/auctionrush/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from auctions import views as auctions_views

urlpatterns = [
    path('', auctions_views.index, name="index"),
    path('myauctions/', auctions_views.my_auctions, name="my_auctions"),
    path('mybids/', auctions_views.my_bids, name="my_bids"),
    path('auctions/', include('auctions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register", views.register, name="register"),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/auctions/urls.py
from django.urls import path

from . import views
app_name = 'auctions'

urlpatterns = [
    path('create/', views.create, name='create'),
    # path('myauctions/', views.my_auctions, name='my_auctions'),
    # Example: /auctions/
    path('', views.auctions, name='auctions'),
    # Example: /auctions/5/
    path('<int:auction_id>/', views.detail, name='detail'),
    # Example: /auctions/5/results/
    # path('<int:auction_id>/results/', views.results, name='results'),
    # Example: /auctions/5/bid/
    path('<int:auction_id>/bid/', views.bid, name='bid'),
]

python/auctions/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta, datetime, timezone
from math import ceil

# Auction duration in minutes
AUCTION_DURATION = 5

class Auction(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    desc = models.CharField(max_length=2000, blank=True)
    image = models.ImageField(upload_to='auction_images/', blank=True, default = 'auction_images/default/default.svg')
    min_value = models.IntegerField()
    date_added = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    winner = models.ForeignKey(User, on_delete=models.SET("(deleted)"),
                               blank=True,
                               null=True,
                               related_name="auction_winner",
                               related_query_name="auction_winner")
    final_value = models.IntegerField(blank=True, null=True)

    def resolve(self):
        if self.is_active:
            # If expired
            if self.has_expired():
                # Define winner
                highest_bid = Bid.objects.filter(auction=self).order_by('-amount').order_by('date').first()
                if highest_bid:
                    self.winner = highest_bid.bidder
                    self.final_value = highest_bid.amount
                self.is_active = False
                self.save()

    # Helper function that determines if the auction has expired
    def has_expired(self):
        now = datetime.now(timezone.utc)
        expiration = self.date_added + timedelta(minutes=AUCTION_DURATION)
        if now > expiration:
            return True
        else:
            return False

    # Returns the ceiling of remaining_time in minutes
    @property
    def remaining_minutes(self):
        if self.is_active:
            now = datetime.now(timezone.utc)
            expiration = self.date_added + timedelta(minutes=AUCTION_DURATION)
            minutes_remaining = ceil((expiration - now).total_seconds() / 60)
            return(minutes_remaining)
        else:
            return(0)

class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    amount = models.IntegerField()
    # is_cancelled = models.BooleanField(default=False)
    date = models.DateTimeField('when the bid was made')

python/auctions/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()

python/auctions/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.decorators import login_required
from datetime import datetime, timezone
from django.urls import reverse

from .models import Auction, Bid
from .forms import ImageUploadForm

# Main page
def index(request):
    # First get all auctions and resolve them
    auction_list = Auction.objects.all()
    for a in auction_list:
        a.resolve()
    # Get all active auctions, oldest first
    latest_auction_list = auction_list.filter(is_active=True).order_by('date_added')
    template = loader.get_template('auctions/index.html')
    context = {
        'title': "Active auctions",
        'auction_list': latest_auction_list,
    }
    return HttpResponse(template.render(context, request))

def auctions(request):
    # Get all auctions, newest first
    auction_list = Auction.objects.order_by('-date_added')
    for a in auction_list:
        a.resolve()
    template = loader.get_template('auctions/index.html')
    context = {
        'title': "All auctions",
        'auction_list': auction_list,
    }
    return HttpResponse(template.render(context, request))

# Details on some auction
def detail(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    auction.resolve()
    already_bid = False
    if request.user.is_authenticated:
        if auction.author == request.user:
            own_auction = True
            return render(request, 'auctions/detail.html', {'auction': auction, 'own_auction': own_auction})

        user_bid = Bid.objects.filter(bidder=request.user).filter(auction=auction).first()
        if user_bid:
            already_bid = True
            bid_amount = user_bid.amount
            return render(request, 'auctions/detail.html', {'auction': auction, 'already_bid': already_bid, 'bid_amount': bid_amount})

    return render(request, 'auctions/detail.html', {'auction': auction, 'already_bid': already_bid})
    # try:
    #     auction = Auction.objects.get(pk=auction_id)
    # except Auction.DoesNotExist:
    #     raise Http404("Auction does not exist")
    # return render(request, 'auctions/detail.html', {'auction': auction})

# def results(request, auction_id):
#     response = "You're looking at the results of auction %s."
#     return HttpResponse(response % auction_id)

# Bid on some auction
@login_required
def bid(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    auction.resolve()
    bid = Bid.objects.filter(bidder=request.user).filter(auction=auction).first()

    if not auction.is_active:
        return render(request, 'auctions/detail.html', {
            'auction': auction,
            'error_message': "The auction has expired.",
        })

    try:
        bid_amount = request.POST['amount']
        # Prevent user from entering an empty or invalid bid
        if not bid_amount or int(bid_amount) < auction.min_value:
            raise(KeyError)
        if not bid:
            # Create new Bid object if it does not exist
            bid = Bid()
            bid.auction = auction
            bid.bidder = request.user
        bid.amount = bid_amount
        bid.date = datetime.now(timezone.utc)
    except (KeyError):
        # Redisplay the auction details.
        return render(request, 'auctions/detail.html', {
            'auction': auction,
            'error_message': "Invalid bid amount.",
        })
    else:
        bid.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        return HttpResponseRedirect(reverse('my_bids', args=()))

        # TODO redirect to my bids
        # template = loader.get_template('auctions/my_bids.html')
        # context = {
        #     'my_bids_list': my_bids_list,
        # }
        # return HttpResponse(template.render(context, request))

        # return HttpResponse(f"You just bid {bid_amount} on auction {auction_id}.")

# Create auction
@login_required
def create(request):
    submit_button = request.POST.get('submit_button')
    if submit_button:
        try:
            title = request.POST['title']
            min_value = request.POST['min_value']
            if not title or not min_value:
                raise(KeyError)
        except (KeyError):
            # Redisplay the create auction page with an error message.
            return render(request, 'auctions/create.html', {
                'error_message': "Please fill the required fields.",
            })
        else:
            # Create new Bid object
            auction = Auction()
            auction.author = request.user
            auction.title = title
            auction.min_value = min_value
            auction.desc = request.POST['description']
            form = ImageUploadForm(request.POST, request.FILES)
            if form.is_valid():
                image = form.cleaned_data['image']
                auction.image = image
            # auction.date_added = datetime.utcnow()
            auction.date_added = datetime.now(timezone.utc)
            auction.save()
            # return HttpResponseRedirect(reverse('auctions:detail', args=(auction.id,)))
            return HttpResponseRedirect(reverse('my_auctions', args=()))
    else:
        return render(request, 'auctions/create.html')


@login_required
def my_auctions(request):
    # Get all auctions by user, sorted by date
    my_auctions_list = Auction.objects.all().filter(author=request.user).order_by('-date_added')
    for a in my_auctions_list:
        a.resolve()
    template = loader.get_template('auctions/my_auctions.html')
    context = {
        'my_auctions_list': my_auctions_list,
    }
    return HttpResponse(template.render(context, request))

@login_required
def my_bids(request):
    # Get all bids by user, sorted by date
    my_bids_list = Bid.objects.all().filter(bidder=request.user).order_by('-date')
    for b in my_bids_list:
        b.auction.resolve()

    template = loader.get_template('auctions/my_bids.html')
    context = {
        'my_bids_list': my_bids_list,
    }
    return HttpResponse(template.render(context, request))

python/auctions/templates/auctions/create.html
{% extends "base.html" %}
{% block content %}

<h1>Create Auction</h1>
<div class="wrapper">
    <form action="{% url 'auctions:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if error_message %}<p class="error"><strong>{{ error_message }}</strong></p>{% endif %}
        <span>Enter title:</span>
        <span class="required_field" >*</span>
        <br>
        <input class="textbox" type="text" name="title">
        <br>
        <br>
        <span>Enter description:</span>
        <br>
        <input class="description_box" type="text" name="description">
        <br>
        <br>
        <span>Upload picture:</span>
        <br>
        <input class="textbox" type="file" accept="image/*" name="image">
        <br>
        <br>
        <span>Enter minimum value:</span>
        <span class="required_field" >*</span>
        <br>
        <input class="textbox" type="text" name="min_value">
        <br>
        <br>
        <input type="submit" class="submit_button" name="submit_button" value="Create">
    </form>
</div>
{% endblock %}

python/auctions/templates/auctions/detail.html
{% extends "base.html" %}
{% block content %}

{% block title %}<title>{{ auction.title }} - Auction Rush</title>{% endblock %}

<h1> {{ auction.title }} </h1>
<div class="wrapper">
    {% if not own_auction %}
        {% if auction.is_active %}
        <!-- <div class="bid_box"> -->
        <form action="{% url 'auctions:bid' auction.id %}" method="post">
        <!-- <form action="/auctions/{{ auction.id }}/bid/" method="post"> -->
        {% csrf_token %}
        <div class=\"input_label\">
        {% if error_message %}<p class="error" ><strong>{{ error_message }}</strong></p>{% endif %}
        {% if already_bid %}
            <h3> Current bid: {{ bid_amount }} </h3>
        {% endif %}
        <span>Enter amount ($):</span>
        <span class="required_field" >*</span>
        </div>
        <input class="textbox" type="text" class="input_box" name="amount">
        <br>
        <a><input class="submit_button" type="submit" class="submit_button" value="Bid"></a>
        </form>
        <br>
        <!-- </div> -->
        {% endif %}
    {% endif %}
</div>
<div class="wrapper">
    <span class="auction-card">
        <span><img class="auction_image_index" src="{{ auction.image.url }}"></span>
            {% if auction.is_active %}
                {% if auction.remaining_minutes < 2 %}
                    <div class="auction-card-urgent">Less than {{ auction.remaining_minutes }}m</div>
                {% else %}
                    <div class="auction-card-active">Less than {{ auction.remaining_minutes }}m</div>
                {% endif %}
            {% else %}
            <div class="auction-card-inactive">Expired</div>
            {% endif %}
            <div class="auction-card-value">{{ auction.min_value }}$</div>
        </div>
    </span>
</div>
{% if auction.desc %}
<div class="wrapper">
    <div class="desc_box">
    <div class="desc_box_title">Description</div>
    <hr>
    {{ auction.desc }}
    </div>
</div>
{% endif %}

{% endblock %}

python/auctions/templates/auctions/index.html
{% extends "base.html" %}
{% block content %}

<h1>{{ title }}</h1>
{% if auction_list %}
    <div class="wrapper">
    {% for auction in auction_list %}
        <a class="auction-card" href="{% url 'auctions:detail' auction.id %}">
            <div><img class="auction_image_index" src="{{ auction.image.url }}"></div>
            <div class="auction-card-title">{{ auction.title }}</div>
            {% if auction.is_active %}
                {% if auction.remaining_minutes < 2 %}
                    <div class="auction-card-urgent">Less than {{ auction.remaining_minutes }}m</div>
                {% else %}
                    <div class="auction-card-active">Less than {{ auction.remaining_minutes }}m</div>
                {% endif %}
            {% else %}
            <div class="auction-card-inactive">Expired</div>
            {% endif %}
            <div class="auction-card-value">{{ auction.min_value }}$</div>
        </a>
        <!-- <li class="auction-card"><a href="{% url 'auctions:detail' auction.id %}">{{ auction.title }}</a></li> -->
    {% endfor %}
    </div>
{% else %}
    <h4>No auctions are available.</h4>
{% endif %}

{% endblock %}

python/auctions/templates/auctions/my_auctions.html
{% extends "base.html" %}
{% block title %}<title>My Auctions - Auction Rush</title>{% endblock %}
{% block content %}

<h2> My auctions </h2>
{% if my_auctions_list %}
    <ul class="my-auction-list">
    {% for auction in my_auctions_list %}
        <li class="my-auction-li"><a class="my-auction-link" href="{% url 'auctions:detail' auction.id %}">{{ auction.title }}</a>
            <hr>
            <div class="my-auction-date">Added: {{ auction.date_added }}</div>
            {% if auction.is_active %}
                <span class="my-auction-status-active">
                    Pending
                </span>
                <span class="my-auction-value">
                    {{ auction.min_value }}$
                </span>
            {% else %}
                {% if auction.final_value %}
                <span class="my-auction-status-resolved">
                    Final value: {{ auction.final_value }}$
                </span>
                {% else %}
                <span class="my-auction-status-no_winner">
                    No winner
                </span>
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <h4>No auctions are available.</h4>
{% endif %}

{% endblock %}

python/auctions/templates/auctions/my_bids.html
{% extends "base.html" %}
{% block title %}<title>My Bids - Auction Rush</title>{% endblock %}
{% block content %}

<h2> My bids </h2>
{% if my_bids_list %}
<ul class="my-bid-list">
    {% for bid in my_bids_list %}
        <li class="my-bid-li"><a class="my-bid-link" href="{% url 'auctions:detail' bid.auction.id %}">{{ bid.auction.title }}</a>
            <hr>
            <div class="my-bid-label">
                My last bid: {{ bid.amount }}$
                <div class="my-bid-date">({{ bid.date }})</div>
            </div>
            {% if bid.auction.is_active %}
                <div class="my-bid-status-active">Pending</div>
            {% else %}
                {% if bid.auction.winner and bid.auction.winner == user %}
                    <div class="my-bid-status-won">Won for {{ bid.amount }}$</div>
                {% else %}
                    <div class="my-bid-status-lost">Lost</div>
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
</ul>
{% else %}
    <h4>No bids are available.</h4>
{% endif %}

{% endblock %}