python/auctionrush/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from auctions import views as auctions_views

urlpatterns = [
    path('', auctions_views.index, name="index"),
    path('myauctions/', auctions_views.my_auctions, name="my_auctions"),
    path('mybids/', auctions_views.my_bids, name="my_bids"),
    path('auctions/', include('auctions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("accounts/register", views.register, name="register"),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/auctions/urls.py
from django.urls import path

from . import views
app_name = 'auctions'

urlpatterns = [
    path('create/', views.create, name='create'),
    # path('myauctions/', views.my_auctions, name='my_auctions'),
    # Example: /auctions/
    path('', views.auctions, name='auctions'),
    # Example: /auctions/5/
    path('<int:auction_id>/', views.detail, name='detail'),
    # Example: /auctions/5/results/
    # path('<int:auction_id>/results/', views.results, name='results'),
    # Example: /auctions/5/bid/
    path('<int:auction_id>/bid/', views.bid, name='bid'),
]

python/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Ubay</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
</head>
<body>
      {% block sidebar %}
        <ul class="navbar">
          <li class="auction-rush-button">
              <a class="navbar-link" href="{% url 'index' %}">
                  Ubay
              </a>
          </li>
          <li class="navbar-item"><a class="navbar-link" href="{% url 'auctions:auctions' %}">All auctions</a></li>
          {% if user.is_authenticated %}
          <li class="navbar-item"><a class="navbar-link" href="{% url 'my_auctions' %}">My auctions</a></li>
          <li class="navbar-item"><a class="navbar-link" href="{% url 'my_bids' %}">My bids</a></li>
          <li class="create-auction-button"><a class="navbar-link" href="{% url 'auctions:create' %}">Create an auction</a> </li>
          {% endif %}
          {% if user.is_authenticated %}
            <li class="navbar-item-right"><a class="navbar-link" href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
            <li class="navbar-item-right"><span class="navbar-text">Logged in as: <span class="username">{{ user.get_username }}</span></span></li>
          {% else %}
            <li class="navbar-item-right"><a class="navbar-link" href="{% url 'login' %}?next={{request.path}}">Login</a></li>
            <li class="navbar-item-right"><a class="navbar-link" href="{% url 'register' %}?next={{request.path}}">Register</a></li>
          {% endif %}
        </ul>
     {% endblock %}
      <div class="main-content">{% block content %}{% endblock %}</div>
</body>
</html>

python/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Flying Dutchman</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- TODO Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <!-- {% load static %} -->
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'auctions/style.css' %}"> -->
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'auctions:index' %}">Home</a></li>
          <li><a href="{% url 'my_auctions' %}">My auctions</a></li>
          <li><a href="{% url 'my_bids' %}">My bids</a></li>
          {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% endif %} 
          </ul>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>